### ISSUE TITLE
Make repository friendly for contributions.

### ISSUE THREAD

**Issue by ultimape** [nsreed/ouronote#36]
We want to think about development processes related to contributions / pull requests etc. So

- [ ] Make it clear to others on how to submit pull requests.
- [ ] A tentative vetting process for contributions (in particular the package.json changes)
- [ ] Some kind of Contribution guidelines.
- [ ] Look into the necessity of Contributor License Agreements.
